export const MessageType = {
  JOIN_ROOM: 'JOIN_ROOM',
  LEAVE_ROOM: 'LEAVE_ROOM',
  USER_LIST: 'USER_LIST',
  DRAW_LINE: 'DRAW_LINE',
  ADD_STICKER: 'ADD_STICKER',
  MOVE_ELEMENT: 'MOVE_ELEMENT',
  DELETE_ELEMENT: 'DELETE_ELEMENT',
  CLEAR_CANVAS: 'CLEAR_CANVAS',
  SYNC_STATE: 'SYNC_STATE',
  OPERATION_LOG: 'OPERATION_LOG'
}

export const ElementType = {
  LINE: 'line',
  STICKER: 'sticker'
}
