import os
import pathlib

BASE_DIR = pathlib.Path(__file__).parent.parent

DB_PATH = BASE_DIR / "studio.db"

THUMBNAIL_DIR = BASE_DIR / "thumbnails"
EXPORT_DIR = BASE_DIR / "exports"
BACKUP_DIR = BASE_DIR / "backups"
LOG_DIR = BASE_DIR / "logs"

THUMBNAIL_SIZE = (200, 200)

SUPPORTED_IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tiff", ".tif", ".webp"}

ORDER_STATUS_PENDING = "待拍摄"
ORDER_STATUS_SHOOTING = "拍摄中"
ORDER_STATUS_SELECTING = "选片中"
ORDER_STATUS_RETOUCHING = "精修中"
ORDER_STATUS_DELIVERING = "交付中"
ORDER_STATUS_COMPLETED = "已完成"
ORDER_STATUS_CANCELLED = "已取消"

ORDER_STATUSES = [
    ORDER_STATUS_PENDING,
    ORDER_STATUS_SHOOTING,
    ORDER_STATUS_SELECTING,
    ORDER_STATUS_RETOUCHING,
    ORDER_STATUS_DELIVERING,
    ORDER_STATUS_COMPLETED,
    ORDER_STATUS_CANCELLED,
]

PAYMENT_STATUS_UNPAID = "未付款"
PAYMENT_STATUS_PARTIAL = "部分付款"
PAYMENT_STATUS_PAID = "已结清"

PAYMENT_STATUSES = [PAYMENT_STATUS_UNPAID, PAYMENT_STATUS_PARTIAL, PAYMENT_STATUS_PAID]

RETOUCH_STATUS_PENDING = "待精修"
RETOUCH_STATUS_IN_PROGRESS = "精修中"
RETOUCH_STATUS_DONE = "已完成"

RETOUCH_STATUSES = [RETOUCH_STATUS_PENDING, RETOUCH_STATUS_IN_PROGRESS, RETOUCH_STATUS_DONE]

APP_NAME = "摄影工作室订单管理系统"
APP_VERSION = "1.0.0"

for d in [THUMBNAIL_DIR, EXPORT_DIR, BACKUP_DIR, LOG_DIR]:
    os.makedirs(d, exist_ok=True)
